### ISSUE TITLE
Is there any information available on RaftKeeper

### ISSUE THREAD

**Issue by liuyuliang092** [JDRaftKeeper/RaftKeeper#45]
is there any introduction documents about RaftKeeper, such as cross-site active-active deployment or how to solve the problem that ZooKeeper cannot break through high-throughput writing and low-latency data replication in ClickHouse? thanks

**Comment by liuyuliang092** [comment]
I would like to ask how long it will take for this user guide to be available? thanks

**Comment by JackyWoo** [comment]
About one weak

**Comment by liuyuliang092** [comment]
Thanks, will it be made public on git if the user guide comes out?

**Comment by JackyWoo** [comment]
Yes

**Comment by JackyWoo** [comment]
@liuyuliang092 unfortunately the doc delayed. But I can provide you some info:

### 1. Cross zone architecture with clickhouse

We deploy RaftKeeper-ClickHouse in a cross zone way. Let's assume we have 3 zone, we put 2 RaftKeeper nodes in zone1, zone2 and put 1 in zone3. Put 2 shard in zone1 and another 2 shard in zone2.

In this architecture:

- One zone crash, the cluster works well.
- User can just import data into one zone, data will be replicated to another. 

### 2. How to speed up CK insert througput?

 Zookeeper restricts the data import speed of ck. Because RaftKeeper has a higher throughput capacity than Zookeeper.  So it speed up CK data importing and in my production experience, it is 1x-5x.

**Comment by liuyuliang092** [comment]
Thank you for your information

**Comment by JackyWoo** [comment]
@liuyuliang092 documents is here  https://github.com/JDRaftKeeper/RaftKeeper/tree/master/docs

**Comment by cangyin** [comment]
>  put 2 RaftKeeper nodes in zone1, zone2 and put 1 in zone3

For keeper to work cross data centers, can we use the Observer mode ?

**Comment by JackyWoo** [comment]
Yes

**Comment by JackyWoo** [comment]
You can use `learner` and `start_as_follower` in your configuration file.
```
<cluster>
            <server>
                <id>1</id>
                <host>host1</host>
                <!-- `true` if this node is learner. Learner will not initiate or participate in leader election. -->
                <learner>false</learner>
                <start_as_follower>false</start_as_follower> 
            </server>
            ......
```

**Comment by cangyin** [comment]
See, thks!
